output_dir: outputs/training/3dgs_res_176_320_views_49
img_size: [176, 320]
num_views: 98
num_input_views: 49
gs_view_chunk_size: 1
num_input_multi_views: 1
batch_size: 4
load_latents: False
max_train_steps: 12500